### ISSUE TITLE
Pass IplImage to SDL_CreateRGBSurfaceFrom

### ISSUE THREAD

**Issue by tahaarian** [javasdl/libjavasdl#1]
Hello sir 

Thank you in advance for your nice api.
Actually we need to implement below code on java with libjavasdl.

SDL_Texture* Cutscene::convertCV_MatToSDL_Texture(const cv::Mat &matImg)
{
    IplImage opencvimg2 = (IplImage)matImg;
    IplImage* opencvimg = &opencvimg2;

     //Convert to SDL_Surface
    frameSurface = SDL_CreateRGBSurfaceFrom(
                         (void*)opencvimg->imageData,
                         opencvimg->width, opencvimg->height,
                         opencvimg->depth*opencvimg->nChannels,
                         opencvimg->widthStep,
                         0xff0000, 0x00ff00, 0x0000ff, 0);

    if(frameSurface == NULL)
    {
        SDL_Log("Couldn't convert Mat to Surface.");
        return NULL;
    }

    //Convert to SDL_Texture
    frameTexture = SDL_CreateTextureFromSurface(
                    GameEngine::getInstance()->getRenderer(), frameSurface);
    if(frameTexture == NULL)
    {
        SDL_Log("Couldn't convert Mat(converted to surface) to Texture.");
        return NULL;
    }
    else
    {
        SDL_Log("SUCCESS conversion");
        return frameTexture;
    }

    cvReleaseImage(&opencvimg);

We have developed according to your api such as below example but we can not cast "opencv_core.IplImage" to jna.Poiner for SDL_CreateRGBSurfaceFrom function

    public void onImageProcessedRaw(opencv_core.Mat mat, int index) {
        Platform.runLater(() -> {
            if(index == 0) {

                if(mat == null)
                    return;

                opencv_core.IplImage opencvimg2 = new opencv_core.IplImage(mat);

                SDL_Surface sdls = SDL_CreateRGBSurfaceFrom(
                        opencvimg2.imageData() //we have problem with this line,
                        opencvimg2.width(), opencvimg2.height(),
                        opencvimg2.depth()*opencvimg2.nChannels(),
                        opencvimg2.widthStep(),
                        0xff0000, 0x00ff00, 0x0000ff, 0);

                if(sdls == null)
                {
                    System.out.println("SDL_Surface Error ");
                    return;
                }

                SDL_Texture texture = SDL_CreateTextureFromSurface(sdlr, sdls);

                if(texture == null)
                {
                    System.out.println("SDL_Texture Error ");
                    return;
                }

                SdlSurface.SDL_FreeSurface(sdls);

                SDL_WaitEvent(event);

                SDL_Rect dstrect = new SDL_Rect();
                dstrect.x = 0;
                dstrect.y = 0;
                dstrect.h = 480;
                dstrect.w = 640;

                SDL_RenderClear(sdlr);
                SDL_RenderCopy(sdlr, texture, null, dstrect);
                SDL_RenderPresent(sdlr);
            }
        });
    }

We will appreciate if you could help us.
Thank you so much 

Taha Arian

**Comment by karlstrings** [comment]
Forgot I wrote this. It is cool that someone is finding it useful.

However, I am now in a role with very strict IP assignment policies which severely restricts my ability to maintain code.

I can't maintain it, but I can transfer the repository to you. Feel free to own it.
